compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_config_file: scripts/zero3_offload.json
  zero3_init_flag: true
  zero3_save_16bit_model: true
  deepspeed_multinode_launcher: standard  
distributed_type: DEEPSPEED
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 2
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

